ARG PROJECT=libadore
ARG LIBADORE_TAG=latest

FROM libadore_build:${LIBADORE_TAG} AS libadore_build

FROM alpine:3.14 AS libadore_package

ARG PROJECT

WORKDIR /tmp/${PROJECT}
COPY --from=libadore_build /tmp/${PROJECT} /tmp/${PROJECT}

