version: '3.4'

services:

  libadore_build:
    image: libadore_build:${LIBADORE_TAG:-latest}
    container_name: libadore_build:${LIBADORE_TAG}
    hostname: libadore_build
    build:
      context: .
      network: host
      dockerfile: Dockerfile.libadore.build
      args:
        - CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH:-}
        - LIBADORE_TAG=${LIBADORE_TAG:-latest}
  
  libadore:
    image: libadore:${LIBADORE_TAG:-latest}
    container_name: libadore:${LIBADORE_TAG}
    hostname: libadore
    depends_on:
      - libadore_build
    build:
      context: .
      network: host
      dockerfile: Dockerfile.libadore
      args:
        - LIBADORE_TAG=${LIBADORE_TAG:-latest}

  libadore_test:
    image: libadore_test:${LIBADORE_TAG:-latest}
    container_name: libadore_test:${LIBADORE_TAG}
    hostname: libadore_test
    depends_on:
      - libadore_build
    build:
      context: .
      network: host
      dockerfile: Dockerfile.libadore.test
      args:
        - LIBADORE_TAG=${LIBADORE_TAG:-latest}
    entrypoint: sh -c 'cd build && ctest 2>&1'
