ARG PROJECT=libadore
ARG LIBADORE_TAG=latest

FROM libadore_build:${LIBADORE_TAG} AS libadore_test_requirements_base

ARG PROJECT
ARG REQUIREMENTS_FILE="requirements.${PROJECT}.ubuntu20.04.test.system"

WORKDIR /tmp/${PROJECT}/${PROJECT}

#RUN apt-get update && \
#    apt-get install --no-install-recommends -y $(sed '/^#/d' ${REQUIREMENTS_FILE}) && \
#    rm -rf /var/lib/apt/lists/*
