version: '3.5'

services: 
  adore-cli:
    privileged: true
    image: adore-cli:${ADORE_CLI_TAG:-latest}
    container_name: adore-cli
    user: adore-cli
    hostname: ADORe-CLI
    network_mode: "host"
    environment:
      - CATKIN_WORKSPACE_DIRECTORY=${CATKIN_WORKSPACE_DIRECTORY:-catkin_workspace}
      - TEST_SCENARIOS=${TEST_SCENARIOS:-baseline_test.launch}
      - "BAG_OUTPUT_DIRECTORY=${ADORE_SOURCE_DIRECTORY}/.log/.ros/bag_files"
      - "ROS_HOME=${ADORE_SOURCE_DIRECTORY}/.log/.ros"
      - "ADORE_SOURCE_DIRECTORY=${ADORE_SOURCE_DIRECTORY}"
      - "HISTFILE=${ADORE_SOURCE_DIRECTORY}/.zsh_history"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
      - "ROS_HOSTNAME=127.0.0.1"
    depends_on:
      #- ros-master  #activate this option if you want to start roscore on startup of adore-cli container
      - plotlabserver  #activate this option if you want to start plotlabserver automatically with adore-cli container
    build:
      context: .
      network: host
      dockerfile: docker/Dockerfile.adore-cli
      args:
        - ADORE_CLI_TAG=${ADORE_CLI_TAG:-latest}
        - USER=adore-cli
        - UID=${UID:-1000}
        - GID=${GID:-1001}
    volumes:
      - ./:/tmp/adore
      - /var/run/docker.sock:/var/run/docker.sock
      - .bash_history:/home/adore-cli/.bash_history
      - ${ADORE_SOURCE_DIRECTORY}:${ADORE_SOURCE_DIRECTORY}
  adore-cli_x11-display:
    privileged: true
    image: adore-cli_x11-display:${ADORE_CLI_TAG:-latest}
    container_name: adore-cli
    user: adore-cli
    hostname: ADORe-CLI
    network_mode: "host"
    environment:
      - DISPLAY_MODE=${DISPLAY_MODE:-native}
      # - DISPLAY_MODE=${DISPLAY_MODE:-window_manager}
      # - DISPLAY_MODE=${DISPLAY_MODE:-headless}
      - CATKIN_WORKSPACE_DIRECTORY=${CATKIN_WORKSPACE_DIRECTORY:-catkin_workspace}
      - DISPLAY=${DISPLAY}
      - UID=${UID}
      - GID=${GID}
      - TEST_SCENARIOS=${TEST_SCENARIOS:-baseline_test.launch}
      - "BAG_OUTPUT_DIRECTORY=${ADORE_SOURCE_DIRECTORY}/.log/.ros/bag_files"
      - "ROS_HOME=${ADORE_SOURCE_DIRECTORY}/.log/.ros"
      - "ADORE_SOURCE_DIRECTORY=${ADORE_SOURCE_DIRECTORY}"
      - "HISTFILE=${ADORE_SOURCE_DIRECTORY}/.zsh_history"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
      - "ROS_HOSTNAME=127.0.0.1"
    depends_on:
      # - ros-master  #activate this option if you want to start roscore on startup of adore-cli container
      - plotlabserver  #activate this option if you want to start plotlabserver automatically with adore-cli container
    build:
      context: .
      network: host
      dockerfile: docker/Dockerfile.adore-cli_x11_display
      args:
        - ADORE_CLI_TAG=${ADORE_CLI_TAG:-latest}
        - ADORE_IF_ROS_TAG=${ADORE_IF_ROS_TAG:-latest}
        - USER=adore-cli
        - UID=${UID:-1000}
        - GID=${GID:-1001}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - .bash_history:/home/adore-cli/.bash_history
      - ./:/tmp/adore
      - ${ADORE_SOURCE_DIRECTORY}:${ADORE_SOURCE_DIRECTORY}     
