# syntax = edrevo/dockerfile-plus

ARG UID=1000
ARG GID=1000
ARG USER=catkin

FROM ros:noetic-ros-core-focal AS catkin_base

ARG UID
ARG GID
ARG USER

RUN apt-get update && \
    apt-get install --no-install-recommends -y make g++ python3-catkin-tools && \
    rm -rf /var/lib/apt/lists/*

RUN useradd catkin

INCLUDE+ Dockerfile.personalize.partial

USER nobody
