#This dockerfile partial installs zsh



ARG USER

USER root
RUN apt-get update && \
    apt-get install --no-install-recommends -y zsh git vim && \
    rm -rf /var/lib/apt/lists/*

USER ${USER}

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended
