# *******************************************************************************
# * Copyright (C) 2017-2020 German Aerospace Center (DLR). 
# * Eclipse ADORe, Automated Driving Open Research https://eclipse.org/adore
# *
# * This program and the accompanying materials are made available under the 
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0 
# *
# * Contributors: 
# *  Jan Lauermann
# ********************************************************************************
#AUTOMATION_NOT_ACTIVE = 0
#GOAL_REACHED = 1
#DRIVING_TO_GOAL = 2
uint8 mission_state