# *******************************************************************************
# * Copyright (C) 2017-2020 German Aerospace Center (DLR). 
# * Eclipse ADORe, Automated Driving Open Research https://eclipse.org/adore
# *
# * This program and the accompanying materials are made available under the 
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0 
# *
# * Contributors: 
# *  Daniel Heß
# ********************************************************************************
#OccupancyCylinder describes occupied space in dimensions x,y,z and t
float64 rxy     #radius in dimensions x and y
float64 x       #center x component
float64 y       #center y component
float64 t0      #time interval start
float64 t1      #time interval end
float64 z0      #z (elevation) interval start
float64 z1      #z (elevation) interval end 